telemetry:
  enabled: true
  interval: 10
  address: localhost:8888

kafka:
  address: ${ZG_KAFKA_ADDRESS}
  group_id: group_id
  user: guest
  password: guest
  topic: processing_1

mongodb:
  url: ${ZG_MONGODB_URL}
  database_name: ${ZG_MONGODB_NAME}

redis:
  address: ${ZG_REDIS_ADDRESS}
  password: ${ZG_REDIS_PASSWORD}
  db: ${ZG_REDIS_DB}