kafka:
  address: ${ZG_KAFKA_ADDRESS:localhost:9092}
  group_id: nosql_repo
  user: guest
  password: guest
  topic: processing_1

dbs:
  mongodbs:
    - ${ZG_MONGODB_URL_1:mongodb://localhost:27017/zg_mongodb}
    - ${ZG_MONGODB_URL_2:mongodb://localhost:27017/zg_mongodb_2}

redis:
  address: ${ZG_REDIS_URL:localhost:6379}
  db: ${ZG_REDIS_DB:0}

logstash:
  url: ${LOGSTASH_URL:http://localhost:5000}

tracer:
  url: ${TRACER_URL:http://localhost:14268/api/traces}
  enabled: true
